#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 

bspc config border_width         1 
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#AUTO STRAT 

# execute sxhkdrc for the keybindings 
sxhkd & 

# execute polybar  
polybar & 

# execute picon config 
picom --config $HOME/.config/picom/picom.conf & 

# execute dunst 
dunst & 

# execute wallpaper changer 
while true ; do $HOME/code/dotfiles-rice/scripts/change_wallpaper.sh	; sleep 300 ; done  

